text2image:
  model-path:
    param-name: "--model-path"
    value: ${TEXT2IMAGE_MODEL_PATH:/stable-diffusion-v1-5}
#    value: "C:\\big-files\\test-sbai\\stable-diffusion-v1-5"
  execution-provider:
    param-name: --execution-provider
    value: ${EXECUTION_PROVIDER:CPU}
  high-quality:
    inference-steps: ${HQ_INFERENCE_STEPS:50}
    image-size: ${HQ_IMAGE_SIZE:1024}
  low-quality:
    inference-steps: ${LQ_INFERENCE_STEPS:15}
    image-size: ${LQ_IMAGE_SIZE:512}
  negative-text: ""
  guide-strength: ${GUIDE_STRENGTH:10.0f}
  batch-size: 1
  rng-seed: 42